### ISSUE TITLE
Git is Already Federated & Decentralized

### ISSUE THREAD

**Issue by davidpgil** [forgefed/forgefed#22]
The following blog post mentions ForgeFed.

https://drewdevault.com/2018/07/23/Git-is-already-distributed.html

**Comment by jaywink** [comment]
The blog post writer joined this group and this fact was discussed on the mailing list [here](https://framalistes.org/sympa/arc/git-federation/2018-07/msg00067.html). ForgeFed is not creating a "federated VCS protocol", but ActivityPub extensions for code hosting. There is a big difference, which was discussed at length on the mailing list, for those interested.

**Comment by yookoala** [comment]
As @jaywink put it, we've already covered this in our discussion. I'm closing this for now.

You're welcome to still comment here if you have new points to bring to light.
