### ISSUE TITLE
GAnarchy - "federated" (not sure if right term) git-based projects

### ISSUE THREAD

**Issue by SoniEx2** [forgefed/forgefed#25]
Please take a look at these:

1. https://ganarchy.github.io/
2. https://ganarchy.autistic.space/
3. https://cybre.space/tags/gan385e734a52e13949a7a5c71827f6de920dbfea43

**Comment by bill-auger** [comment]
please explain how this relates to forge federation

what does it do?
how does it work?

**Comment by SoniEx2** [comment]
it doesn't federate code, it only federates issues... well not yet but anyway that's part of the goal.

other than that it's basically trying to remove the upstream. because upstreams are bad. instead, everything should be decentralized and integrated. it's meant to integrate with the fediverse using web+ganarchy links, which should be overriden on a per-(mastodon-)instance basis to point to admin-chosen ganarchy instances. this seems more important to the whole federated thing than actual federation, as it then becomes about user choice and curation.

the idea of static pages makes it easy for anyone to run it - you can set it up on github.io or on your own server or whatnot, as there's no server-side code.

by checking ganarchy instances with your project on them, you don't need PRs. also ppl don't need to know how to code to use this, they just need to know how to merge things. this gives ppl the power of curation. the power of curating features. if a lot of ppl like a feature then a lot of ppl can merge that feature and then a large amount of the repos will contain that feature, making that feature more likely to spread further.

it's not feature-complete, but it's definitely usable in production! (i.e. production-ready) while it doesn't (yet) have a federation protocol, and ActivityPub support turns out to be... difficult, to say the least, it's still quite nice IMO.

every project has a project commit. you can take that project commit's and use it on the fediverse as a hashtag, as in https://cybre.space/tags/gan385e734a52e13949a7a5c71827f6de920dbfea43 - this is basically a federated issue tracker with no central authority, but with great moderation/curation potential. I just couldn't figure out a way to pull these in because AP doesn't have an endpoint for it.

**Comment by SoniEx2** [comment]
I call it "federated" because of the whole curation thing. I'd like it to be proper-federated at some point (yet still have the curation thing ofc), but I'm not too bothered by it.

**Comment by SoniEx2** [comment]
it definitely federates now: https://github.com/ganarchy/ganarchy.github.io/blob/master/private/targets.txt

and you can even fork whole instances: https://github.com/ganarchy/ganarchy.github.io
