### ISSUE TITLE
Define a project commit format

### ISSUE THREAD

**Issue by SoniEx2** [forgefed/forgefed#27]
GAnarchy has this thing called a "project commit". It uses the following format:

```text
[Project] {{Title}}

{{Description}}
```

`Title` may not contain newlines and `Description` may contain anything. However, I don't feel like it's worthwhile to keep it GAnarchy-specific. As such, I'd like to propose a common project commit format that anything can use. It would still follow the same basic structure, but we can adapt some things. We could add an YAML section or something, or define the description to be markdown-based, or so on. Maybe it should also be allowed to refer to any files available at the moment of the project commit, which would be useful for a project logo. This would benefit any tools doing anything even remotely like GAnarchy. I'd need to adapt GAnarchy to handle the new format, but if we stick to plaintext formats, it shouldn't be a big deal.

**Comment by techknowlogick** [comment]
Per #26 this repo is no longer the correct place to discuss forgefed, please refer to that PR for instructions on where the best place to discuss forgefed.

**Comment by SoniEx2** [comment]
oh. thanks. apologies.
