### ISSUE TITLE
Forgefed videoconference - June 13th 2pm UTC

### ISSUE THREAD

**Issue by bill-auger** [forgefed/forgefed#29]
there has been renewed interest in forge-fed recently by forge developers and other related projects from the forge-friends group - an online conference is planned to discuss future development, infrastructure, and management of forge-fed - as always, the community is invited to participate

Location: https://meet.jit.si/ForgefedMeeting
Date: June 13th 2pm UTC
Details: https://forum.forgefriends.org/t/forgefed-videoconference-june-13th-2pm-utc/715

**Comment by 6543** [comment]
long: https://cloud.forgefriends.org/s/6sex8Z2GLDxKDAa
tldr:
 - new repo: https://codeberg.org/ForgeFed/ForgeFed
   - to have CI  and more granular settings
   - push mirror
   - pages server (static site hosting) like github-pages but foss
 - new **tld** domain! -> https://forgefed.org
 - forum is social-hub
 - document more stuff
